# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home:
    text:
    fa: home
    link: /
#  Archives:
#    text:
#    fa: archive
#    link: archives
  About:
    text:
    fa: user
    link: about


social:
  email:
  twitter:
  weibo:
  github:
  googleplus:
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: #disqus _shortname
google_analytics: #UA-89421276-1
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code
